SQL CHALLENGE — DAY 23
YOUR ANSWER + CORRECT ANSWER
============================================================

Q1 — CUSTOMER MONTHLY ORDER CONSISTENCY
============================================================

RESULT: ✗ INCORRECT

## YOUR ANSWER:

WITH PAYMENT_SUMMARY AS
(SELECT  
	O.ORDER_ID,
	(CASE WHEN P.STATUS = 'SUCCESSFUL' THEN 1 ELSE 0 END) AS PAYMENT_COUNT,
	(CASE WHEN P.STATUS = 'SUCCESSFUL' THEN P.AMOUNT ELSE 0 END) AS PAYMENT_AMOUNT
FROM ORDERS O LEFT JOIN PAYMENT P
	ON O.ORDER_ID = P.ORDER_ID
GROUP BY 
	O.ORDER_ID),

ORDER_SUMMARY AS (
SELECT 
	ORDER_ID,
	CUSTOMER_ID,
	STORE_ID,
	STATUS,
	TOTAL_AMOUNT,
	NVL(PAYMENT_COUNT,0) AS PAYMENT_COUNT,
	NVL(PAYMENT_AMOUNT,0) AS PAYMENT_AMOUNT
FROM ORDERS O LEFT JOIN PAYMENT_SUMMARY PS
	ON O.ORDER_ID = PS.ORDER_ID
WHERE 
	O.ORDER_DATE >= DATE '2026-12-01' AND 
	O.ORDER_DATE < DATE '2027-01-01'
),

CUSTOMER_SUMMARY AS(
SELECT OS.CUSTOMER_ID,
COUNT(CASE WHEN STATUS ='COMPLETED' THEN 1 END) AS COMPLETED_ORDER_COUNT,
COUNT(CASE WHEN STATUS ='CANCELLED' THEN 1 END) AS CANCELLED_ORDER_COUNT,
SUM(CASE WHEN STATUS ='COMPLETED' THEN TOTAL_AMOUNT ELSE 0 END) AS TOTAL_COMPLETED_AMOUNT,
COUNT(CASE WHEN STATUS ='COMPLETED' THEN STORE_ID END) AS STORE_COUNT,
COUNT(CASE WHEN STATUS ='COMPLETED' AND PAYMENT_COUNT > 1 THEN 1 END) AS MULTI_PAYMENT_ORDER_COUNT,
SUM(CASE WHEN STATUS ='COMPLETED' AND PAYMENT_AMOUNT = 0  THEN 1 END) AS UNPAID_ORDER_COUNT
FROM ORDER_SUMMARY OS
GROUP BY CUSTOMER_ID
)

SELECT 
	C.CUSTOMER_ID,
	C.CUSTOMER_NAME,
	CS.COMPLETED_ORDER_COUNT,
	CS.TOTAL_COMPLETED_AMOUNT,
	CS.STORE_COUNT,
	CS.MULTI_PAYMENT_ORDER_COUNT,
	CS.UNPAID_ORDER_COUNT
FROM 
	CUSTOMER C JOIN CUSTOMER_SUMMARY CS
	ON C.CUSTOMER_ID = CS.CUSTOMER_ID
WHERE 
C.STATUS = 'ACTIVE' AND
CS.COMPLETED_ORDER_COUNT >= 5 AND
	CS.TOTAL_COMPLETED_AMOUNT >= 100000 AND
	CS.STORE_COUNT >= 3 AND
	CS.MULTI_PAYMENT_ORDER_COUNT >=1 AND 
	CS.UNPAID_ORDER_COUNT	>= 1 AND
CS.CANCELLED_ORDER_COUNT = 0;

## CORRECT ANSWER:

WITH PAYMENT_SUMMARY AS
(
    SELECT
        O.ORDER_ID,
        COUNT(CASE WHEN P.STATUS = 'SUCCESSFUL' THEN 1 END) AS PAYMENT_COUNT,
        SUM(CASE WHEN P.STATUS = 'SUCCESSFUL' THEN P.AMOUNT ELSE 0 END) AS PAYMENT_AMOUNT
    FROM ORDERS O
    LEFT JOIN PAYMENT P
        ON O.ORDER_ID = P.ORDER_ID
    GROUP BY O.ORDER_ID
),
ORDER_SUMMARY AS
(
    SELECT
        O.ORDER_ID,
        O.CUSTOMER_ID,
        O.STORE_ID,
        O.STATUS,
        O.TOTAL_AMOUNT,
        NVL(PS.PAYMENT_COUNT,0) AS PAYMENT_COUNT,
        NVL(PS.PAYMENT_AMOUNT,0) AS PAYMENT_AMOUNT
    FROM ORDERS O
    LEFT JOIN PAYMENT_SUMMARY PS
        ON O.ORDER_ID = PS.ORDER_ID
    WHERE O.ORDER_DATE >= DATE '2026-12-01'
      AND O.ORDER_DATE < DATE '2027-01-01'
),
CUSTOMER_SUMMARY AS
(
    SELECT
        CUSTOMER_ID,
        COUNT(CASE WHEN STATUS = 'COMPLETED' THEN 1 END) AS COMPLETED_ORDER_COUNT,
        COUNT(CASE WHEN STATUS = 'CANCELLED' THEN 1 END) AS CANCELLED_ORDER_COUNT,
        SUM(CASE WHEN STATUS = 'COMPLETED' THEN TOTAL_AMOUNT ELSE 0 END) AS TOTAL_COMPLETED_AMOUNT,
        COUNT(DISTINCT CASE WHEN STATUS = 'COMPLETED' THEN STORE_ID END) AS STORE_COUNT,
        COUNT(CASE WHEN STATUS = 'COMPLETED' AND PAYMENT_COUNT > 1 THEN 1 END) AS MULTI_PAYMENT_ORDER_COUNT,
        COUNT(CASE WHEN STATUS = 'COMPLETED' AND PAYMENT_COUNT = 0 THEN 1 END) AS UNPAID_ORDER_COUNT
    FROM ORDER_SUMMARY
    GROUP BY CUSTOMER_ID
)
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    CS.COMPLETED_ORDER_COUNT,
    CS.TOTAL_COMPLETED_AMOUNT,
    CS.STORE_COUNT,
    CS.MULTI_PAYMENT_ORDER_COUNT,
    CS.UNPAID_ORDER_COUNT
FROM CUSTOMER C
JOIN CUSTOMER_SUMMARY CS
    ON C.CUSTOMER_ID = CS.CUSTOMER_ID
WHERE C.STATUS = 'ACTIVE'
  AND CS.COMPLETED_ORDER_COUNT >= 5
  AND CS.TOTAL_COMPLETED_AMOUNT > 100000
  AND CS.STORE_COUNT >= 3
  AND CS.MULTI_PAYMENT_ORDER_COUNT >= 1
  AND CS.UNPAID_ORDER_COUNT >= 1
  AND CS.CANCELLED_ORDER_COUNT = 0;

## EXPLANATION:

Your overall architecture points in the right direction, but the PAYMENT_SUMMARY is not actually aggregating payment rows correctly.

You select P.STATUS and P.AMOUNT directly while grouping only by ORDER_ID. In Oracle, those columns must be aggregated or grouped.

STORE_COUNT also counts completed order rows rather than different stores. The requirement is at least 3 different stores.

Finally, the amount condition is > 100000, not >= 100000.

## EXACT MISTAKES:

1. PAYMENT_SUMMARY does not aggregate payment rows correctly.
2. P.STATUS and P.AMOUNT are selected without aggregation/grouping.
3. STORE_COUNT uses COUNT(STORE_ID) instead of COUNT(DISTINCT STORE_ID).
4. TOTAL_COMPLETED_AMOUNT uses >= 100000 instead of > 100000.

## WHY THIS MISTAKE HAPPENED:

You identified the required payment-to-order reduction, but the actual aggregation step was not completed.

## KEY PATTERN / LESSON:

Reduce PAYMENT to exactly one row per ORDER_ID before joining it to ORDERS and aggregating to CUSTOMER.

Q2 — LATEST STATUS PER PRODUCT
============================================================

RESULT: ⚠ PARTIALLY CORRECT

## YOUR ANSWER:

WITH SALES_SUMMARY AS(
SELECT 
	PRODUCT_ID,
	MAX(TRANSACTION_DATE) AS LATEST_TRANSACTION_DATE,
	SUM(CASE WHEN STATUS = 'COMPLETED' THEN AMOUNT ELSE 0 END ) AS COMPLETED_AMOUNT,
	SUM(CASE WHEN STATUS = 'CANCELLED' THEN 1 ELSE 0 END ) AS CANCELLED_COUNT,
	COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT,
	COUNT(*) AS TOTAL_TRANSACTION_COUNT,	
FROM 
	SALES S
GROUP BY 
	PRODUCT_ID
)

SELECT 
	P.PRODUCT_ID,
	P.PRODUCT_NAME,
	SS.LATEST_TRANSACTION_DATE,
	(SELECT STATUS FROM SALES WHERE PRODUCT_ID = P.PRODUCT_ID AND TRANSACTION_DATE = SS.LATEST_TRANSACTION_DATE)LATEST_STATUS,
	SS.TOTAL_TRANSACTION_COUNT,
	SS.CUSTOMER_COUNT,
	SS.COMPLETED_AMOUNT
FROM 
	PRODUCT P JOIN SALES_SUMMARY SS
	ON P.PRODUCT_ID = SS.PRODUCT_ID
WHERE 
(SELECT STATUS FROM SALES WHERE PRODUCT_ID = P.PRODUCT_ID AND TRANSACTION_DATE = SS.LATEST_TRANSACTION_DATE) = 'COMPLETED' AND 
SS.TOTAL_TRANSACTION_COUNT >= 5 AND 
SS.CUSTOMER_COUNT >= 2 AND 
SS.CANCELLED_COUNT =0 AND
SS.COMPLETED_AMOUNT > 50000

## CORRECT ANSWER:

WITH RANKED_SALES AS
(
    SELECT
        S.*,
        ROW_NUMBER() OVER
        (
            PARTITION BY PRODUCT_ID
            ORDER BY TRANSACTION_DATE DESC, SALE_ID DESC
        ) AS RN
    FROM SALES S
),
PRODUCT_SUMMARY AS
(
    SELECT
        PRODUCT_ID,
        COUNT(*) AS TOTAL_TRANSACTION_COUNT,
        COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT,
        SUM(CASE WHEN STATUS = 'COMPLETED' THEN AMOUNT ELSE 0 END) AS COMPLETED_AMOUNT,
        COUNT(CASE WHEN STATUS = 'CANCELLED' THEN 1 END) AS CANCELLED_COUNT
    FROM SALES
    GROUP BY PRODUCT_ID
)
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    R.TRANSACTION_DATE AS LATEST_TRANSACTION_DATE,
    R.STATUS AS LATEST_STATUS,
    S.TOTAL_TRANSACTION_COUNT,
    S.CUSTOMER_COUNT,
    S.COMPLETED_AMOUNT
FROM PRODUCT P
JOIN RANKED_SALES R
    ON R.PRODUCT_ID = P.PRODUCT_ID
   AND R.RN = 1
JOIN PRODUCT_SUMMARY S
    ON S.PRODUCT_ID = P.PRODUCT_ID
WHERE R.STATUS = 'COMPLETED'
  AND S.TOTAL_TRANSACTION_COUNT >= 5
  AND S.CUSTOMER_COUNT >= 2
  AND S.CANCELLED_COUNT = 0
  AND S.COMPLETED_AMOUNT > 50000;

## EXPLANATION:

Your product-level summary logic is mostly correct.

The immediate syntax error is the trailing comma after COUNT(*).

The larger issue is latest-row selection. MAX(TRANSACTION_DATE) identifies the latest date, but it does not uniquely identify the latest transaction row when multiple transactions have the same date.

ROW_NUMBER() should identify the actual latest row, with SALE_ID as a deterministic tie-breaker.

## EXACT MISTAKES:

1. Trailing comma after COUNT(*) causes a syntax error.
2. The scalar subquery for latest status can return multiple rows when dates tie.
3. MAX(TRANSACTION_DATE) identifies a date, not necessarily one latest row.

## WHY THIS MISTAKE HAPPENED:

You correctly identified the latest date but treated the latest date as equivalent to the latest transaction row.

## KEY PATTERN / LESSON:

Use ROW_NUMBER() to select the actual latest row deterministically.

Q3 — EMPLOYEE SALARY PROGRESSION
============================================================

RESULT: ✗ INCORRECT

## YOUR ANSWER:

WITH SALARY_SUMMARY AS
(SELECT 
	ES.EMP_ID,
	ES.DEPT_ID,
	ES.SALARY,
	ES.EFFECTIVE_DATE,
	DENSE_RANK() OVER(PARTITION BY ES.EMP_ID OVER ES.EFFECTIVE_DATE DESC) AS RN 
FROM EMPLOYEE_SALARY ES),

TOP3SAL AS 
(
SELECT 
	ES.EMP_ID,
	ES.DEPT_ID,
	ES.SALARY,
	ES.EFFECTIVE_DATE,
	RN 
FROM SALARY_SUMMARY ES
WHERE RN <= 3
),
DEPT_AVG AS 
(SELECT 
	ES.EMP_ID,
	ES.DEPT_ID,
	(CASE WHEN RN = 2 THEN ES.SALARY ELSE 0 END) AS PREVIOUS_SALARY,
	(CASE WHEN RN = 1 THEN ES.SALARY ELSE 0 END) AS LATEST_SALARY,
	(SELECT AVG (SALARY) FROM TOP3SAL WHERE DEPT_ID= ES.DEPT_ID) AS DEPT_AVG_LATEST_SALARY
FROM TOP3SAL )

SELECT 
	D.EMP_ID,
	D.DEPT_ID,
	D.PREVIOUS_SALARY,
	D.LATEST_SALARY,
	(D.PREVIOUS_SALARY - D.LATEST_SALARY) AS SALARY_INCREASE,
	((D.PREVIOUS_SALARY - D.LATEST_SALARY)/D.PREVIOUS_SALARY) * 100 AS INCREASE_PERCENTAGE,
	DEPT_AVG_LATEST_SALARY
FROM 
DEPT_AVG
WHERE 
D.PREVIOUS_SALARY < D.LATEST_SALARY AND 
(((D.PREVIOUS_SALARY - D.LATEST_SALARY)/D.PREVIOUS_SALARY) * 100) BETWEEN 10 AND 25 AND 
D.LATEST_SALARY > DEPT_AVG_LATEST_SALARY;

## CORRECT ANSWER:

WITH SALARY_RANKED AS
(
    SELECT
        ES.*,
        ROW_NUMBER() OVER
        (
            PARTITION BY EMP_ID
            ORDER BY EFFECTIVE_DATE DESC
        ) AS RN,
        COUNT(*) OVER (PARTITION BY EMP_ID) AS SALARY_RECORD_COUNT
    FROM EMPLOYEE_SALARY ES
),
LATEST AS
(
    SELECT
        EMP_ID,
        DEPT_ID,
        SALARY AS LATEST_SALARY
    FROM SALARY_RANKED
    WHERE RN = 1
),
PREVIOUS AS
(
    SELECT
        EMP_ID,
        SALARY AS PREVIOUS_SALARY
    FROM SALARY_RANKED
    WHERE RN = 2
),
DEPT_AVG AS
(
    SELECT
        DEPT_ID,
        AVG(LATEST_SALARY) AS DEPT_AVG_LATEST_SALARY
    FROM LATEST
    GROUP BY DEPT_ID
)
SELECT
    L.EMP_ID,
    L.DEPT_ID,
    PR.PREVIOUS_SALARY,
    L.LATEST_SALARY,
    L.LATEST_SALARY - PR.PREVIOUS_SALARY AS SALARY_INCREASE,
    ((L.LATEST_SALARY - PR.PREVIOUS_SALARY) / PR.PREVIOUS_SALARY) * 100 AS INCREASE_PERCENTAGE,
    D.DEPT_AVG_LATEST_SALARY
FROM LATEST L
JOIN PREVIOUS PR
    ON PR.EMP_ID = L.EMP_ID
JOIN DEPT_AVG D
    ON D.DEPT_ID = L.DEPT_ID
JOIN SALARY_RANKED R
    ON R.EMP_ID = L.EMP_ID
   AND R.RN = 1
WHERE R.SALARY_RECORD_COUNT >= 3
  AND L.LATEST_SALARY > PR.PREVIOUS_SALARY
  AND ((L.LATEST_SALARY - PR.PREVIOUS_SALARY) / PR.PREVIOUS_SALARY) * 100 BETWEEN 10 AND 25
  AND L.LATEST_SALARY > D.DEPT_AVG_LATEST_SALARY;

## EXPLANATION:

There are several fundamental problems.

The DENSE_RANK syntax is invalid because OVER appears twice.

The department average is calculated from TOP3SAL, which contains up to three salary records per employee. The requirement is the average of only the latest salary for each employee.

Your salary increase is also reversed: it must be latest salary minus previous salary.

The final query references alias D even though DEPT_AVG is not aliased as D.

## EXACT MISTAKES:

1. Invalid window syntax: OVER appears twice.
2. Department average uses TOP3SAL instead of latest salary per employee.
3. SALARY_INCREASE is previous - latest instead of latest - previous.
4. INCREASE_PERCENTAGE is also reversed.
5. At least 3 salary records is not correctly enforced.
6. Alias D is referenced without defining DEPT_AVG as D.

## WHY THIS MISTAKE HAPPENED:

You combined latest/previous extraction and department aggregation before stabilizing the employee-level grain.

## KEY PATTERN / LESSON:

First isolate latest and previous rows per employee. Then calculate the department average from one latest row per employee.

Q4 — STORE/PRODUCT REVENUE RANKING
============================================================

RESULT: ✗ INCORRECT

## YOUR ANSWER:

WITH SALE_SUMMARY AS(
SELECT
 STORE_ID,
 PRODUCT_ID,
 CUSTOMER_ID,
 SUM(AMOUNT) AS PRODUCT_REVENUE
FROM SALES S
WHERE
S.SALE_DATE >= DATE'2026-11-01' AND 
S.SALE_DATE < DATE '2026-12-01'
GROUP BY 
STORE_ID,
PRODUCT_ID,
CUSTOMER_ID
),
SALE_RANK AS(
SELECT 
SS.STORE_ID,
SS.PRODUCT_ID,
SUM(SS.PRODUCT_REVENUE) AS PRODUCT_REVENUE,
COUNT(SS.CUSTOMER_ID) AS CUSTOMER_COUNT,
COUNT(SS.STORE_ID) AS STORE_COUNT
FROM SALE_SUMMARY SS
GROUP BY 
SS.STORE_ID,
SS.PRODUCT_ID
),
STORE_SUMMRY AS 
(SELECT
SR.STORE_ID,
SR.PRODUCT_ID
SR.PRODUCT_REVENUE
ROW_NUMBER() OVER(PARTITION BY SR.STORE_ID ORDER BY SR.PRODUCT_REVENUE DESC) AS STORE_PRODUCT_RANK
SR.CUSTOMER_COUNT
FROM STORE) 

SELECT 
	S.STORE_ID,
	S.STORE_NAME,
	SS.PRODUCT_ID,
	SS.PRODUCT_REVENUE,
	SS.STORE_PRODUCT_RANK,
	SS.CUSTOMER_COUNT
FROM 
STORE S JOIN STORE_SUMMRY SS
ON S.STORE_ID = SS.STORE_ID
WHERE SS.PRODUCT_REVENUE > 50000
AND SS.STORE_PRODUCT_RANK >= 2
AND SS.CUSTOMER_COUNT>=3

## CORRECT ANSWER:

WITH PRODUCT_SUMMARY AS
(
    SELECT
        S.STORE_ID,
        S.PRODUCT_ID,
        SUM(CASE WHEN S.STATUS = 'COMPLETED' THEN S.AMOUNT ELSE 0 END) AS PRODUCT_REVENUE,
        COUNT(DISTINCT S.CUSTOMER_ID) AS CUSTOMER_COUNT,
        COUNT(CASE WHEN S.STATUS = 'CANCELLED' THEN 1 END) AS CANCELLED_COUNT
    FROM SALES S
    WHERE S.SALE_DATE >= DATE '2026-11-01'
      AND S.SALE_DATE < DATE '2026-12-01'
    GROUP BY S.STORE_ID, S.PRODUCT_ID
),
RANKED_PRODUCTS AS
(
    SELECT
        PS.*,
        ROW_NUMBER() OVER
        (
            PARTITION BY STORE_ID
            ORDER BY PRODUCT_REVENUE DESC
        ) AS STORE_PRODUCT_RANK
    FROM PRODUCT_SUMMARY PS
)
SELECT
    ST.STORE_ID,
    ST.STORE_NAME,
    RP.PRODUCT_ID,
    RP.PRODUCT_REVENUE,
    RP.STORE_PRODUCT_RANK,
    RP.CUSTOMER_COUNT
FROM STORE ST
JOIN RANKED_PRODUCTS RP
    ON RP.STORE_ID = ST.STORE_ID
WHERE RP.PRODUCT_REVENUE > 50000
  AND RP.STORE_PRODUCT_RANK <= 2
  AND RP.CUSTOMER_COUNT >= 3
  AND RP.CANCELLED_COUNT = 0;

## EXPLANATION:

You understood that aggregation must happen before ranking, but the implementation has multiple issues.

Your first CTE creates STORE + PRODUCT + CUSTOMER and then re-aggregates. The required ranking grain is STORE + PRODUCT.

The ranking CTE has syntax errors, reads FROM STORE instead of the aggregated sales CTE, and the rank condition is reversed.

You also did not restrict revenue to COMPLETED transactions or check for CANCELLED transactions.

## EXACT MISTAKES:

1. Missing comma before ROW_NUMBER().
2. Missing comma before SR.CUSTOMER_COUNT.
3. Ranking CTE uses FROM STORE instead of the aggregated sales CTE.
4. Rank condition >= 2 is reversed; rank 1 or 2 requires <= 2.
5. Revenue is not restricted to COMPLETED transactions.
6. No CANCELLED transaction condition.
7. Customer count should be COUNT(DISTINCT CUSTOMER_ID).

## WHY THIS MISTAKE HAPPENED:

You understood the aggregate → rank sequence, but the CTE driving table and final rank direction were not checked.

## KEY PATTERN / LESSON:

Use SALES → STORE+PRODUCT aggregation → RANK within STORE → filter rank <= 2.

Q5 — LEAD-LEVEL ORDER/PAYMENT RECONCILIATION
============================================================

RESULT: ⚠ PARTIALLY CORRECT

## YOUR ANSWER:

WITH PAYMENT_SUMMARY AS(
SELECT O.ORDER_ID,
	   SUM(CASE WHEN P.STATUS = 'SUCCESS' THEN P.AMOUNT ELSE 0 END) AS TOTAL_SUCCESS_PAYMENT,
	   COUNT(CASE WHEN P.STATUS = 'SUCCESS' THEN 1 END) AS SUCCESS_PAYMENT_COUNT
FROM ORDERS O LEFT JOIN PAYMENT P
ON O.ORDER_ID = P.ORDER_ID
GROUP BY O.ORDER_ID),

ORDER_SUMMARY AS(
SELECT O.ORDER_ID,
	   O.CUSTOMER_ID,
	   O.STORE_ID,
	   O.STATUS,
	   O.TOTAL_AMOUNT,
	   NVL(PS.TOTAL_SUCCESS_PAYMENT,0) AS TOTAL_SUCCESS_PAYMENT,
	   NVL(PS.SUCCESS_PAYMENT_COUNT,0) AS SUCCESS_PAYMENT_COUNT
FROM ORDERS O LEFT JOIN PAYMENT_SUMMARY PS
ON O.ORDER_ID = PS.ORDER_ID
WHERE O.ORDER_DATE >= DATE '2026-12-01' AND 
O.ORDER_DATE < DATE '2027-01-01'
),

CUSTOMER_SUMMARY AS(
SELECT OS.CUSTOMER_ID,
COUNT(CASE WHEN OS.STATUS ='COMPLETED' THEN 1 END) AS COMPLETED_ORDER_COUNT,
COUNT(CASE WHEN OS.STATUS ='CANCELLED' THEN 1 END) AS CANCELLED_ORDER_COUNT,
SUM(CASE WHEN OS.STATUS ='COMPLETED' THEN OS.TOTAL_AMOUNT ELSE 0 END) AS TOTAL_ORDER_AMOUNT,
SUM(CASE WHEN OS.STATUS ='COMPLETED' THEN OS.TOTAL_SUCCESS_PAYMENT ELSE 0 END) AS TOTAL_SUCCESS_PAYMENT,
COUNT(DISTINCT CASE WHEN OS.STATUS ='COMPLETED' THEN OS.STORE_ID END) AS STORE_COUNT,
SUM(CASE WHEN OS.STATUS ='COMPLETED' AND OS.TOTAL_SUCCESS_PAYMENT = 0 THEN 1 ELSE 0 END) AS UNPAID_ORDER_COUNT,
SUM(CASE WHEN OS.STATUS ='COMPLETED' AND OS.TOTAL_SUCCESS_PAYMENT > 0 AND  
OS.TOTAL_SUCCESS_PAYMENT < OS.TOTAL_AMOUNT
THEN 1 ELSE 0 END) AS PARTIALLY_PAID_ORDER_COUNT,
SUM(CASE WHEN OS.STATUS ='COMPLETED' AND OS.TOTAL_SUCCESS_PAYMENT >= OS.TOTAL_AMOUNT  THEN 1 ELSE 0 END) AS PAID_ORDER_COUNT,
SUM(CASE WHEN OS.STATUS ='COMPLETED' AND OS.TOTAL_SUCCESS_PAYMENT > 0 THEN 1 ELSE 0 END) AS SUCCESS_PAYMENT_ORDER_COUNT,
COUNT(CASE WHEN SUCCESS_PAYMENT_COUNT > 1 THEN OS.ORDER_ID
    END
) AS MULTI_SUCCESS_PAYMENT_ORDER_COUNT
FROM ORDER_SUMMARY OS 
GROUP BY OS.CUSTOMER_ID
)

SELECT 
		C.CUSTOMER_ID,
		C.CUSTOMER_NAME,
		CS.COMPLETED_ORDER_COUNT,
		CS.TOTAL_ORDER_AMOUNT,
		CS.TOTAL_SUCCESS_PAYMENT,
		CS.STORE_COUNT,
		CS.UNPAID_ORDER_COUNT,
		CS.PARTIALLY_PAID_ORDER_COUNT,
		CS.PAID_ORDER_COUNT,
		CS.SUCCESS_PAYMENT_ORDER_COUNT,
		CS.MULTI_SUCCESS_PAYMENT_ORDER_COUNT,
		(CS.TOTAL_ORDER_AMOUNT - CS.TOTAL_SUCCESS_PAYMENT) AS OUTSTANDING_AMOUNT
FROM 
 CUSTOMER C JOIN CUSTOMER_SUMMARY CS
 ON C.CUSTOMER_ID = CS.CUSTOMER_ID
 WHERE
		CS.COMPLETED_ORDER_COUNT >= 7 AND 
		CS.CANCELLED_ORDER_COUNT = 0 AND 
		CS.TOTAL_ORDER_AMOUNT > 200000 AND
		CS.STORE_COUNT >= 3 AND
		CS.UNPAID_ORDER_COUNT>=2 AND
		CS.PARTIALLY_PAID_ORDER_COUNT >= 2 AND
		CS.PAID_ORDER_COUNT >= 5 AND 
		CS.TOTAL_ORDER_AMOUNT > CS.TOTAL_SUCCESS_PAYMENT AND 
		CS.MULTI_SUCCESS_PAYMENT_ORDER_COUNT >= 2;

## CORRECT ANSWER:

WITH PAYMENT_SUMMARY AS
(
    SELECT
        O.ORDER_ID,
        SUM(CASE WHEN P.STATUS = 'SUCCESS' THEN P.AMOUNT ELSE 0 END) AS TOTAL_SUCCESS_PAYMENT,
        COUNT(CASE WHEN P.STATUS = 'SUCCESS' THEN 1 END) AS SUCCESS_PAYMENT_COUNT
    FROM ORDERS O
    LEFT JOIN PAYMENT P
        ON O.ORDER_ID = P.ORDER_ID
    GROUP BY O.ORDER_ID
),
ORDER_SUMMARY AS
(
    SELECT
        O.ORDER_ID,
        O.CUSTOMER_ID,
        O.STORE_ID,
        O.STATUS,
        O.TOTAL_AMOUNT,
        NVL(PS.TOTAL_SUCCESS_PAYMENT,0) AS TOTAL_SUCCESS_PAYMENT,
        NVL(PS.SUCCESS_PAYMENT_COUNT,0) AS SUCCESS_PAYMENT_COUNT
    FROM ORDERS O
    LEFT JOIN PAYMENT_SUMMARY PS
        ON O.ORDER_ID = PS.ORDER_ID
    WHERE O.ORDER_DATE >= DATE '2026-12-01'
      AND O.ORDER_DATE < DATE '2027-01-01'
),
CUSTOMER_SUMMARY AS
(
    SELECT
        OS.CUSTOMER_ID,
        COUNT(CASE WHEN OS.STATUS = 'COMPLETED' THEN 1 END) AS COMPLETED_ORDER_COUNT,
        COUNT(CASE WHEN OS.STATUS = 'CANCELLED' THEN 1 END) AS CANCELLED_ORDER_COUNT,
        SUM(CASE WHEN OS.STATUS = 'COMPLETED' THEN OS.TOTAL_AMOUNT ELSE 0 END) AS TOTAL_ORDER_AMOUNT,
        SUM(CASE WHEN OS.STATUS = 'COMPLETED' THEN OS.TOTAL_SUCCESS_PAYMENT ELSE 0 END) AS TOTAL_SUCCESS_PAYMENT,
        COUNT(DISTINCT CASE WHEN OS.STATUS = 'COMPLETED' THEN OS.STORE_ID END) AS STORE_COUNT,
        COUNT(CASE WHEN OS.STATUS = 'COMPLETED' AND OS.TOTAL_SUCCESS_PAYMENT = 0 THEN 1 END) AS UNPAID_ORDER_COUNT,
        COUNT(CASE WHEN OS.STATUS = 'COMPLETED'
                   AND OS.TOTAL_SUCCESS_PAYMENT > 0
                   AND OS.TOTAL_SUCCESS_PAYMENT < OS.TOTAL_AMOUNT THEN 1 END) AS PARTIALLY_PAID_ORDER_COUNT,
        COUNT(CASE WHEN OS.STATUS = 'COMPLETED'
                   AND OS.TOTAL_SUCCESS_PAYMENT >= OS.TOTAL_AMOUNT THEN 1 END) AS PAID_ORDER_COUNT,
        COUNT(CASE WHEN OS.STATUS = 'COMPLETED'
                   AND OS.TOTAL_SUCCESS_PAYMENT > 0 THEN 1 END) AS SUCCESS_PAYMENT_ORDER_COUNT,
        COUNT(CASE WHEN OS.STATUS = 'COMPLETED'
                   AND OS.SUCCESS_PAYMENT_COUNT > 1 THEN 1 END) AS MULTI_SUCCESS_PAYMENT_ORDER_COUNT
    FROM ORDER_SUMMARY OS
    GROUP BY OS.CUSTOMER_ID
)
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    CS.COMPLETED_ORDER_COUNT,
    CS.TOTAL_ORDER_AMOUNT,
    CS.TOTAL_SUCCESS_PAYMENT,
    CS.STORE_COUNT,
    CS.UNPAID_ORDER_COUNT,
    CS.PARTIALLY_PAID_ORDER_COUNT,
    CS.PAID_ORDER_COUNT,
    CS.SUCCESS_PAYMENT_ORDER_COUNT,
    CS.MULTI_SUCCESS_PAYMENT_ORDER_COUNT,
    CS.TOTAL_ORDER_AMOUNT - CS.TOTAL_SUCCESS_PAYMENT AS OUTSTANDING_AMOUNT
FROM CUSTOMER C
JOIN CUSTOMER_SUMMARY CS
    ON C.CUSTOMER_ID = CS.CUSTOMER_ID
WHERE C.STATUS = 'ACTIVE'
  AND CS.COMPLETED_ORDER_COUNT >= 7
  AND CS.CANCELLED_ORDER_COUNT = 0
  AND CS.TOTAL_ORDER_AMOUNT > 200000
  AND CS.STORE_COUNT >= 3
  AND CS.UNPAID_ORDER_COUNT >= 2
  AND CS.PARTIALLY_PAID_ORDER_COUNT >= 2
  AND CS.PAID_ORDER_COUNT >= 2
  AND CS.SUCCESS_PAYMENT_ORDER_COUNT >= 5
  AND CS.TOTAL_ORDER_AMOUNT > CS.TOTAL_SUCCESS_PAYMENT
  AND CS.MULTI_SUCCESS_PAYMENT_ORDER_COUNT >= 2;

## EXPLANATION:

Your core architecture is strong:

PAYMENT → ORDER → CUSTOMER

You correctly aggregate payments to order level, classify orders, and aggregate the classifications to customer level.

The main errors are in the final qualification conditions. The question requires at least 2 PAID orders, not 5.

You also missed the ACTIVE customer condition and the requirement for at least 5 different orders with SUCCESS payments.

The multi-success count should be restricted to COMPLETED orders.

## EXACT MISTAKES:

1. PAID_ORDER_COUNT >= 5 should be >= 2.
2. C.STATUS = 'ACTIVE' is missing.
3. SUCCESS_PAYMENT_ORDER_COUNT >= 5 is missing.
4. MULTI_SUCCESS_PAYMENT_ORDER_COUNT should count COMPLETED orders only.
5. Final qualification conditions were not checked one-by-one against every requirement.

## WHY THIS MISTAKE HAPPENED:

The main grain and reconciliation architecture were correct, but the final qualification stage was rushed.

## KEY PATTERN / LESSON:

For Lead-level reconciliation, build the order-level facts first, then translate every business requirement into an explicit customer-level condition.

============================================================
DAY 23 FINAL RESULT
============================================================

FULLY CORRECT: 0
PARTIALLY CORRECT: 2
WRONG: 3

STRICT SCORE:
0 / 5 = 0.00%

EFFECTIVE ACCURACY:
(0 + 2 × 0.5) / 5 = 20.00%

============================================================
DAY 23 — CORE LESSON
============================================================

Q5 shows that your overall Lead-level architecture is improving.

You are increasingly able to preserve the correct business grain through:

PAYMENT
→ ORDER
→ CUSTOMER

The main gap is implementation precision: aggregation grain, latest-row selection, ranking stage, final qualification conditions, and syntax.

============================================================
DAY 23 — PRIORITY LESSONS
============================================================

1. PAYMENT → ORDER aggregation:
   Always produce exactly one row per ORDER_ID.

2. Latest-row problems:
   MAX(DATE) finds the latest date; ROW_NUMBER() identifies the latest row.

3. Latest + previous salary:
   Stabilize employee-level rows before calculating department-level averages.

4. Aggregate → rank:
   First calculate STORE + PRODUCT revenue, then rank within STORE.

5. COUNT(DISTINCT):
   When the requirement says "different", explicitly use DISTINCT.

6. Final qualification:
   Map every business requirement to one final condition.

7. Syntax check:
   Check CASE END, commas, aliases, JOIN ON, and parentheses before submission.

============================================================
NO REWRITE PRACTICE
============================================================


# CUMULATIVE STATUS THROUGH DAY 23

Historical Day 1–14
* Correct: 30
* Partial: 29
* Wrong: 10
* Questions: 70

### Day 15
* Correct: 1
* Partial: 2
* Wrong: 2

### Day 16
* Correct: 3
* Partial: 1
* Wrong: 1

### Day 17
* Correct: 0
* Partial: 2
* Wrong: 3

### Day 18
* Correct: 0
* Partial: 0
* Wrong: 5

### Day 19
* Correct: 0
* Partial: 4
* Wrong: 1

### Day 20
* Correct: 0
* Partial: 3
* Wrong: 2

### Day 21
* Correct: 1
* Partial: 2
* Wrong: 2

### Day 22
* Correct: 0
* Partial: 3
* Wrong: 2

### Day 23
* Correct: 0
* Partial: 2
* Wrong: 3

### CUMULATIVE
* **Correct: 35**
* **Partial: 48**
* **Wrong: 31**
* **Questions: 115**

> The historical Day 1–7 baseline contains a one-question classification-count inconsistency, so the category counts do not sum to the 115-question total. The historical baseline is preserved rather than silently changed.

### CUMULATIVE STRICT SCORE
**35 / 115 = 30.43%**

### CUMULATIVE EFFECTIVE ACCURACY
**(35 + 48 × 0.5) / 115 = 51.30%**